//go:build go1.22

// Package frontendapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package frontendapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for DesiredState.
const (
	DesiredStateDeleted DesiredState = "deleted"
	DesiredStateRunning DesiredState = "running"
	DesiredStateStopped DesiredState = "stopped"
)

// Valid indicates whether the value is a known member of the DesiredState enum.
func (e DesiredState) Valid() bool {
	switch e {
	case DesiredStateDeleted:
		return true
	case DesiredStateRunning:
		return true
	case DesiredStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for Phase.
const (
	PhaseDeleting Phase = "deleting"
	PhaseFailed   Phase = "failed"
	PhasePending  Phase = "pending"
	PhaseRunning  Phase = "running"
	PhaseStarting Phase = "starting"
	PhaseStopped  Phase = "stopped"
	PhaseStopping Phase = "stopping"
)

// Valid indicates whether the value is a known member of the Phase enum.
func (e Phase) Valid() bool {
	switch e {
	case PhaseDeleting:
		return true
	case PhaseFailed:
		return true
	case PhasePending:
		return true
	case PhaseRunning:
		return true
	case PhaseStarting:
		return true
	case PhaseStopped:
		return true
	case PhaseStopping:
		return true
	default:
		return false
	}
}

// CreateEnvironment defines model for CreateEnvironment.
type CreateEnvironment struct {
	CPUs      int    `json:"cpus"`
	Image     string `json:"image"`
	MemoryMiB int    `json:"memory_mib"`

	// Name A DNS label, since it becomes a hostname.
	Name string `json:"name"`
}

// DesiredState What the environment's owner has asked for.
type DesiredState string

// Environment defines model for Environment.
type Environment struct {
	CPUs      int       `json:"cpus"`
	CreatedAt time.Time `json:"created_at"`

	// Desired What the environment's owner has asked for.
	Desired   DesiredState `json:"desired"`
	ID        string       `json:"id"`
	Image     string       `json:"image"`
	MemoryMiB int          `json:"memory_mib"`
	Name      string       `json:"name"`

	// Phase What the environment is doing, as its worker last reported. "pending" means no worker has reported on it yet.
	Phase Phase `json:"phase"`

	// Reason Why the environment is in its phase, when there is more to say.
	Reason    *string   `json:"reason,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`

	// Worker That worker's name.
	Worker *string `json:"worker,omitempty"`

	// WorkerID The worker it is placed on. Absent until placed.
	WorkerID *string `json:"worker_id,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Phase What the environment is doing, as its worker last reported. "pending" means no worker has reported on it yet.
type Phase string

// Resources defines model for Resources.
type Resources struct {
	CPUs      int `json:"cpus"`
	MemoryMiB int `json:"memory_mib"`
}

// Worker defines model for Worker.
type Worker struct {
	Allocated  Resources         `json:"allocated"`
	Capacity   Resources         `json:"capacity"`
	CreatedAt  time.Time         `json:"created_at"`
	ID         string            `json:"id"`
	Labels     map[string]string `json:"labels"`
	LastSeenAt *time.Time        `json:"last_seen_at,omitempty"`
	Name       string            `json:"name"`
	Online     bool              `json:"online"`
	Revoked    bool              `json:"revoked"`

	// Unknown Environments the worker is running that the server has no record of. Reported, never stopped automatically.
	Unknown []string `json:"unknown"`
}

// ID defines model for ID.
type ID = string

// Conflict defines model for Conflict.
type Conflict = Error

// Invalid defines model for Invalid.
type Invalid = Error

// NotFound defines model for NotFound.
type NotFound = Error

// CreateEnvironmentJSONRequestBody defines body for CreateEnvironment for application/json ContentType.
type CreateEnvironmentJSONRequestBody = CreateEnvironment

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/frontend/environments)
	ListEnvironments(w http.ResponseWriter, r *http.Request)

	// (POST /api/frontend/environments)
	CreateEnvironment(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/frontend/environments/{id})
	DeleteEnvironment(w http.ResponseWriter, r *http.Request, id ID)

	// (GET /api/frontend/environments/{id})
	GetEnvironment(w http.ResponseWriter, r *http.Request, id ID)

	// (POST /api/frontend/environments/{id}/start)
	StartEnvironment(w http.ResponseWriter, r *http.Request, id ID)

	// (POST /api/frontend/environments/{id}/stop)
	StopEnvironment(w http.ResponseWriter, r *http.Request, id ID)

	// (GET /api/frontend/workers)
	ListWorkers(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/frontend/workers/{id})
	DeleteWorker(w http.ResponseWriter, r *http.Request, id ID)

	// (POST /api/frontend/workers/{id}/revoke)
	RevokeWorker(w http.ResponseWriter, r *http.Request, id ID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEnvironments operation middleware
func (siw *ServerInterfaceWrapper) ListEnvironments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEnvironments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEnvironment operation middleware
func (siw *ServerInterfaceWrapper) CreateEnvironment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEnvironment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEnvironment operation middleware
func (siw *ServerInterfaceWrapper) DeleteEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEnvironment operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartEnvironment operation middleware
func (siw *ServerInterfaceWrapper) StartEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopEnvironment operation middleware
func (siw *ServerInterfaceWrapper) StopEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkers operation middleware
func (siw *ServerInterfaceWrapper) ListWorkers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorker operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorker(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorker(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeWorker operation middleware
func (siw *ServerInterfaceWrapper) RevokeWorker(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeWorker(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/frontend/environments", wrapper.ListEnvironments)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/frontend/environments", wrapper.CreateEnvironment)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/frontend/environments/{id}", wrapper.DeleteEnvironment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/frontend/environments/{id}", wrapper.GetEnvironment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/frontend/environments/{id}/start", wrapper.StartEnvironment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/frontend/environments/{id}/stop", wrapper.StopEnvironment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/frontend/workers", wrapper.ListWorkers)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/frontend/workers/{id}", wrapper.DeleteWorker)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/frontend/workers/{id}/revoke", wrapper.RevokeWorker)

	return m
}

type ConflictJSONResponse Error

type InvalidJSONResponse Error

type NotFoundJSONResponse Error

type ListEnvironmentsRequestObject struct {
}

type ListEnvironmentsResponseObject interface {
	VisitListEnvironmentsResponse(w http.ResponseWriter) error
}

type ListEnvironments200JSONResponse []Environment

func (response ListEnvironments200JSONResponse) VisitListEnvironmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEnvironmentRequestObject struct {
	Body *CreateEnvironmentJSONRequestBody
}

type CreateEnvironmentResponseObject interface {
	VisitCreateEnvironmentResponse(w http.ResponseWriter) error
}

type CreateEnvironment201JSONResponse Environment

func (response CreateEnvironment201JSONResponse) VisitCreateEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEnvironment400JSONResponse struct{ InvalidJSONResponse }

func (response CreateEnvironment400JSONResponse) VisitCreateEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEnvironment409JSONResponse struct{ ConflictJSONResponse }

func (response CreateEnvironment409JSONResponse) VisitCreateEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type DeleteEnvironmentResponseObject interface {
	VisitDeleteEnvironmentResponse(w http.ResponseWriter) error
}

type DeleteEnvironment200JSONResponse Environment

func (response DeleteEnvironment200JSONResponse) VisitDeleteEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEnvironment204Response struct {
}

func (response DeleteEnvironment204Response) VisitDeleteEnvironmentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteEnvironment404JSONResponse) VisitDeleteEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type GetEnvironmentResponseObject interface {
	VisitGetEnvironmentResponse(w http.ResponseWriter) error
}

type GetEnvironment200JSONResponse Environment

func (response GetEnvironment200JSONResponse) VisitGetEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEnvironment404JSONResponse) VisitGetEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type StartEnvironmentResponseObject interface {
	VisitStartEnvironmentResponse(w http.ResponseWriter) error
}

type StartEnvironment200JSONResponse Environment

func (response StartEnvironment200JSONResponse) VisitStartEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response StartEnvironment404JSONResponse) VisitStartEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartEnvironment409JSONResponse struct{ ConflictJSONResponse }

func (response StartEnvironment409JSONResponse) VisitStartEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StopEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type StopEnvironmentResponseObject interface {
	VisitStopEnvironmentResponse(w http.ResponseWriter) error
}

type StopEnvironment200JSONResponse Environment

func (response StopEnvironment200JSONResponse) VisitStopEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response StopEnvironment404JSONResponse) VisitStopEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopEnvironment409JSONResponse struct{ ConflictJSONResponse }

func (response StopEnvironment409JSONResponse) VisitStopEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkersRequestObject struct {
}

type ListWorkersResponseObject interface {
	VisitListWorkersResponse(w http.ResponseWriter) error
}

type ListWorkers200JSONResponse []Worker

func (response ListWorkers200JSONResponse) VisitListWorkersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWorkerRequestObject struct {
	ID ID `json:"id"`
}

type DeleteWorkerResponseObject interface {
	VisitDeleteWorkerResponse(w http.ResponseWriter) error
}

type DeleteWorker204Response struct {
}

func (response DeleteWorker204Response) VisitDeleteWorkerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteWorker404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteWorker404JSONResponse) VisitDeleteWorkerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWorker409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteWorker409JSONResponse) VisitDeleteWorkerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeWorkerRequestObject struct {
	ID ID `json:"id"`
}

type RevokeWorkerResponseObject interface {
	VisitRevokeWorkerResponse(w http.ResponseWriter) error
}

type RevokeWorker204Response struct {
}

func (response RevokeWorker204Response) VisitRevokeWorkerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeWorker404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeWorker404JSONResponse) VisitRevokeWorkerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/frontend/environments)
	ListEnvironments(ctx context.Context, request ListEnvironmentsRequestObject) (ListEnvironmentsResponseObject, error)

	// (POST /api/frontend/environments)
	CreateEnvironment(ctx context.Context, request CreateEnvironmentRequestObject) (CreateEnvironmentResponseObject, error)

	// (DELETE /api/frontend/environments/{id})
	DeleteEnvironment(ctx context.Context, request DeleteEnvironmentRequestObject) (DeleteEnvironmentResponseObject, error)

	// (GET /api/frontend/environments/{id})
	GetEnvironment(ctx context.Context, request GetEnvironmentRequestObject) (GetEnvironmentResponseObject, error)

	// (POST /api/frontend/environments/{id}/start)
	StartEnvironment(ctx context.Context, request StartEnvironmentRequestObject) (StartEnvironmentResponseObject, error)

	// (POST /api/frontend/environments/{id}/stop)
	StopEnvironment(ctx context.Context, request StopEnvironmentRequestObject) (StopEnvironmentResponseObject, error)

	// (GET /api/frontend/workers)
	ListWorkers(ctx context.Context, request ListWorkersRequestObject) (ListWorkersResponseObject, error)

	// (DELETE /api/frontend/workers/{id})
	DeleteWorker(ctx context.Context, request DeleteWorkerRequestObject) (DeleteWorkerResponseObject, error)

	// (POST /api/frontend/workers/{id}/revoke)
	RevokeWorker(ctx context.Context, request RevokeWorkerRequestObject) (RevokeWorkerResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEnvironments operation middleware
func (sh *strictHandler) ListEnvironments(w http.ResponseWriter, r *http.Request) {
	var request ListEnvironmentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEnvironments(ctx, request.(ListEnvironmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEnvironments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEnvironmentsResponseObject); ok {
		if err := validResponse.VisitListEnvironmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEnvironment operation middleware
func (sh *strictHandler) CreateEnvironment(w http.ResponseWriter, r *http.Request) {
	var request CreateEnvironmentRequestObject

	var body CreateEnvironmentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEnvironment(ctx, request.(CreateEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEnvironmentResponseObject); ok {
		if err := validResponse.VisitCreateEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEnvironment operation middleware
func (sh *strictHandler) DeleteEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request DeleteEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEnvironment(ctx, request.(DeleteEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEnvironmentResponseObject); ok {
		if err := validResponse.VisitDeleteEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEnvironment operation middleware
func (sh *strictHandler) GetEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request GetEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironment(ctx, request.(GetEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEnvironmentResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartEnvironment operation middleware
func (sh *strictHandler) StartEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request StartEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartEnvironment(ctx, request.(StartEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartEnvironmentResponseObject); ok {
		if err := validResponse.VisitStartEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopEnvironment operation middleware
func (sh *strictHandler) StopEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request StopEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopEnvironment(ctx, request.(StopEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopEnvironmentResponseObject); ok {
		if err := validResponse.VisitStopEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWorkers operation middleware
func (sh *strictHandler) ListWorkers(w http.ResponseWriter, r *http.Request) {
	var request ListWorkersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWorkers(ctx, request.(ListWorkersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWorkers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWorkersResponseObject); ok {
		if err := validResponse.VisitListWorkersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteWorker operation middleware
func (sh *strictHandler) DeleteWorker(w http.ResponseWriter, r *http.Request, id ID) {
	var request DeleteWorkerRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWorker(ctx, request.(DeleteWorkerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWorker")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteWorkerResponseObject); ok {
		if err := validResponse.VisitDeleteWorkerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeWorker operation middleware
func (sh *strictHandler) RevokeWorker(w http.ResponseWriter, r *http.Request, id ID) {
	var request RevokeWorkerRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeWorker(ctx, request.(RevokeWorkerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeWorker")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeWorkerResponseObject); ok {
		if err := validResponse.VisitRevokeWorkerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
