//go:build go1.22

// Package clientapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package clientapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AddLoginKey defines model for AddLoginKey.
type AddLoginKey struct {
	// Name Absent takes the key's own comment.
	Name *string `json:"name,omitempty"`

	// PublicKey In authorized_keys form, as in ~/.ssh/id_ed25519.pub.
	PublicKey string `json:"public_key"`
}

// Environment defines model for Environment.
type Environment struct {
	CPUs      *int      `json:"cpus,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// Desired What its owner asked for -- running, stopped, suspended or deleted. More may come.
	Desired string `json:"desired"`

	// Display Its display -- none or desktop. More may come.
	Display *string `json:"display,omitempty"`

	// EditorPath The folder an editor opens in it.
	EditorPath *string `json:"editor_path,omitempty"`
	ID         string  `json:"id"`
	MemoryMiB  *int    `json:"memory_mib,omitempty"`
	Name       string  `json:"name"`

	// Owner The owner's username.
	Owner   string `json:"owner"`
	OwnerID string `json:"owner_id"`

	// Phase What it is doing, as its worker last reported: pending, starting, running, stopping, stopped, suspending, suspended, failed, deleting. More may come; treat one you do not know as busy.
	Phase string `json:"phase"`

	// Progress How far a start has got: its step -- download, unpack, disks, boot, network, workspace, in that order, more may come -- and, where the step can be measured, done of total in unit (bytes or objects), at rate a second lately.
	Progress *StartProgress `json:"progress,omitempty"`

	// Reason Why it is in its phase, when there is more to say.
	Reason   *string `json:"reason,omitempty"`
	Template string  `json:"template"`

	// UpdatedAt When its phase last changed.
	UpdatedAt time.Time `json:"updated_at"`

	// Worker The worker it runs on, once placed.
	Worker *string `json:"worker,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// LoginKey defines model for LoginKey.
type LoginKey struct {
	CreatedAt time.Time `json:"created_at"`

	// Fingerprint SHA256:..., as ssh-keygen -l prints it.
	Fingerprint string `json:"fingerprint"`
	ID          string `json:"id"`
	Name        string `json:"name"`
}

// Me defines model for Me.
type Me struct {
	Admin       bool   `json:"admin"`
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`

	// SSH Where the SSH gateway is: ssh <environment>@<host> -p <port>, or <owner>/<environment> for someone else's. Absent when the server runs none.
	SSH      *SSHGateway `json:"ssh,omitempty"`
	Username string      `json:"username"`
}

// SSHGateway Where the SSH gateway is: ssh <environment>@<host> -p <port>, or <owner>/<environment> for someone else's. Absent when the server runs none.
type SSHGateway struct {
	Host string `json:"host"`

	// HostKey The gateway's public host key, in known_hosts form without the host name.
	HostKey string `json:"host_key"`
	Port    int    `json:"port"`
}

// StartProgress How far a start has got: its step -- download, unpack, disks, boot, network, workspace, in that order, more may come -- and, where the step can be measured, done of total in unit (bytes or objects), at rate a second lately.
type StartProgress struct {
	Done  *int64   `json:"done,omitempty"`
	Rate  *float32 `json:"rate,omitempty"`
	Step  string   `json:"step"`
	Total *int64   `json:"total,omitempty"`
	Unit  *string  `json:"unit,omitempty"`
}

// Version defines model for Version.
type Version struct {
	// Server The server's build, for display.
	Server string `json:"server"`

	// Versions The API versions this server serves, oldest first: "v1", and in time more. A client uses the newest it knows.
	Versions []string `json:"versions"`
}

// ID defines model for ID.
type ID = string

// Conflict defines model for Conflict.
type Conflict = Error

// Invalid defines model for Invalid.
type Invalid = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// AddLoginKeyJSONRequestBody defines body for AddLoginKey for application/json ContentType.
type AddLoginKeyJSONRequestBody = AddLoginKey

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListEnvironments Every environment the user can reach, oldest first
	// (GET /environments)
	ListEnvironments(w http.ResponseWriter, r *http.Request)
	// GetEnvironment One environment
	// (GET /environments/{id})
	GetEnvironment(w http.ResponseWriter, r *http.Request, id ID)
	// StartEnvironment Ask for an environment to run
	// (POST /environments/{id}/start)
	StartEnvironment(w http.ResponseWriter, r *http.Request, id ID)
	// StopEnvironment Ask for an environment to stop, keeping its disks
	// (POST /environments/{id}/stop)
	StopEnvironment(w http.ResponseWriter, r *http.Request, id ID)
	// SuspendEnvironment Ask for an environment to suspend, keeping its memory on disk
	// (POST /environments/{id}/suspend)
	SuspendEnvironment(w http.ResponseWriter, r *http.Request, id ID)
	// GetMe The signed-in user, and how to reach their environments over SSH
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// ListLoginKeys The public keys that sign the user in over SSH
	// (GET /me/login-keys)
	ListLoginKeys(w http.ResponseWriter, r *http.Request)
	// AddLoginKey Add a public key that signs the user in over SSH
	// (POST /me/login-keys)
	AddLoginKey(w http.ResponseWriter, r *http.Request)
	// GetVersion Which versions of this API the server serves, and its build
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEnvironments operation middleware
func (siw *ServerInterfaceWrapper) ListEnvironments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEnvironments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEnvironment operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartEnvironment operation middleware
func (siw *ServerInterfaceWrapper) StartEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopEnvironment operation middleware
func (siw *ServerInterfaceWrapper) StopEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SuspendEnvironment operation middleware
func (siw *ServerInterfaceWrapper) SuspendEnvironment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SuspendEnvironment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLoginKeys operation middleware
func (siw *ServerInterfaceWrapper) ListLoginKeys(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLoginKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddLoginKey operation middleware
func (siw *ServerInterfaceWrapper) AddLoginKey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddLoginKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me/login-keys", wrapper.ListLoginKeys)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/me/login-keys", wrapper.AddLoginKey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/environments", wrapper.ListEnvironments)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/environments/{id}", wrapper.GetEnvironment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/environments/{id}/start", wrapper.StartEnvironment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/environments/{id}/stop", wrapper.StopEnvironment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/environments/{id}/suspend", wrapper.SuspendEnvironment)

	return m
}

type ConflictJSONResponse Error

type EnvironmentJSONResponse Environment

type InvalidJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListEnvironmentsRequestObject struct {
}

type ListEnvironmentsResponseObject interface {
	VisitListEnvironmentsResponse(w http.ResponseWriter) error
}

type ListEnvironments200JSONResponse []Environment

func (response ListEnvironments200JSONResponse) VisitListEnvironmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEnvironments401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListEnvironments401JSONResponse) VisitListEnvironmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type GetEnvironmentResponseObject interface {
	VisitGetEnvironmentResponse(w http.ResponseWriter) error
}

type GetEnvironment200JSONResponse Environment

func (response GetEnvironment200JSONResponse) VisitGetEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEnvironment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEnvironment401JSONResponse) VisitGetEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEnvironment404JSONResponse) VisitGetEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type StartEnvironmentResponseObject interface {
	VisitStartEnvironmentResponse(w http.ResponseWriter) error
}

type StartEnvironment200JSONResponse struct{ EnvironmentJSONResponse }

func (response StartEnvironment200JSONResponse) VisitStartEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartEnvironment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StartEnvironment401JSONResponse) VisitStartEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response StartEnvironment404JSONResponse) VisitStartEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartEnvironment409JSONResponse struct{ ConflictJSONResponse }

func (response StartEnvironment409JSONResponse) VisitStartEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StopEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type StopEnvironmentResponseObject interface {
	VisitStopEnvironmentResponse(w http.ResponseWriter) error
}

type StopEnvironment200JSONResponse struct{ EnvironmentJSONResponse }

func (response StopEnvironment200JSONResponse) VisitStopEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopEnvironment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StopEnvironment401JSONResponse) VisitStopEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response StopEnvironment404JSONResponse) VisitStopEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopEnvironment409JSONResponse struct{ ConflictJSONResponse }

func (response StopEnvironment409JSONResponse) VisitStopEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SuspendEnvironmentRequestObject struct {
	ID ID `json:"id"`
}

type SuspendEnvironmentResponseObject interface {
	VisitSuspendEnvironmentResponse(w http.ResponseWriter) error
}

type SuspendEnvironment200JSONResponse struct{ EnvironmentJSONResponse }

func (response SuspendEnvironment200JSONResponse) VisitSuspendEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SuspendEnvironment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SuspendEnvironment401JSONResponse) VisitSuspendEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SuspendEnvironment404JSONResponse struct{ NotFoundJSONResponse }

func (response SuspendEnvironment404JSONResponse) VisitSuspendEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SuspendEnvironment409JSONResponse struct{ ConflictJSONResponse }

func (response SuspendEnvironment409JSONResponse) VisitSuspendEnvironmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListLoginKeysRequestObject struct {
}

type ListLoginKeysResponseObject interface {
	VisitListLoginKeysResponse(w http.ResponseWriter) error
}

type ListLoginKeys200JSONResponse []LoginKey

func (response ListLoginKeys200JSONResponse) VisitListLoginKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLoginKeys401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListLoginKeys401JSONResponse) VisitListLoginKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AddLoginKeyRequestObject struct {
	Body *AddLoginKeyJSONRequestBody
}

type AddLoginKeyResponseObject interface {
	VisitAddLoginKeyResponse(w http.ResponseWriter) error
}

type AddLoginKey201JSONResponse LoginKey

func (response AddLoginKey201JSONResponse) VisitAddLoginKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AddLoginKey400JSONResponse struct{ InvalidJSONResponse }

func (response AddLoginKey400JSONResponse) VisitAddLoginKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AddLoginKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AddLoginKey401JSONResponse) VisitAddLoginKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse Version

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListEnvironments Every environment the user can reach, oldest first
	// (GET /environments)
	ListEnvironments(ctx context.Context, request ListEnvironmentsRequestObject) (ListEnvironmentsResponseObject, error)
	// GetEnvironment One environment
	// (GET /environments/{id})
	GetEnvironment(ctx context.Context, request GetEnvironmentRequestObject) (GetEnvironmentResponseObject, error)
	// StartEnvironment Ask for an environment to run
	// (POST /environments/{id}/start)
	StartEnvironment(ctx context.Context, request StartEnvironmentRequestObject) (StartEnvironmentResponseObject, error)
	// StopEnvironment Ask for an environment to stop, keeping its disks
	// (POST /environments/{id}/stop)
	StopEnvironment(ctx context.Context, request StopEnvironmentRequestObject) (StopEnvironmentResponseObject, error)
	// SuspendEnvironment Ask for an environment to suspend, keeping its memory on disk
	// (POST /environments/{id}/suspend)
	SuspendEnvironment(ctx context.Context, request SuspendEnvironmentRequestObject) (SuspendEnvironmentResponseObject, error)
	// GetMe The signed-in user, and how to reach their environments over SSH
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// ListLoginKeys The public keys that sign the user in over SSH
	// (GET /me/login-keys)
	ListLoginKeys(ctx context.Context, request ListLoginKeysRequestObject) (ListLoginKeysResponseObject, error)
	// AddLoginKey Add a public key that signs the user in over SSH
	// (POST /me/login-keys)
	AddLoginKey(ctx context.Context, request AddLoginKeyRequestObject) (AddLoginKeyResponseObject, error)
	// GetVersion Which versions of this API the server serves, and its build
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEnvironments operation middleware
func (sh *strictHandler) ListEnvironments(w http.ResponseWriter, r *http.Request) {
	var request ListEnvironmentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEnvironments(ctx, request.(ListEnvironmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEnvironments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEnvironmentsResponseObject); ok {
		if err := validResponse.VisitListEnvironmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEnvironment operation middleware
func (sh *strictHandler) GetEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request GetEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironment(ctx, request.(GetEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEnvironmentResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartEnvironment operation middleware
func (sh *strictHandler) StartEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request StartEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartEnvironment(ctx, request.(StartEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartEnvironmentResponseObject); ok {
		if err := validResponse.VisitStartEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopEnvironment operation middleware
func (sh *strictHandler) StopEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request StopEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopEnvironment(ctx, request.(StopEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopEnvironmentResponseObject); ok {
		if err := validResponse.VisitStopEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SuspendEnvironment operation middleware
func (sh *strictHandler) SuspendEnvironment(w http.ResponseWriter, r *http.Request, id ID) {
	var request SuspendEnvironmentRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SuspendEnvironment(ctx, request.(SuspendEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuspendEnvironment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SuspendEnvironmentResponseObject); ok {
		if err := validResponse.VisitSuspendEnvironmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLoginKeys operation middleware
func (sh *strictHandler) ListLoginKeys(w http.ResponseWriter, r *http.Request) {
	var request ListLoginKeysRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLoginKeys(ctx, request.(ListLoginKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLoginKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLoginKeysResponseObject); ok {
		if err := validResponse.VisitListLoginKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddLoginKey operation middleware
func (sh *strictHandler) AddLoginKey(w http.ResponseWriter, r *http.Request) {
	var request AddLoginKeyRequestObject

	var body AddLoginKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddLoginKey(ctx, request.(AddLoginKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddLoginKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddLoginKeyResponseObject); ok {
		if err := validResponse.VisitAddLoginKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
