// The frontend API, typed from internal/frontendapi/openapi.yaml. The types in
// gen/ are generated by `npm run gen:api`; a path, parameter or field that
// does not match the spec fails to compile.

import createClient from 'openapi-fetch'

import type { components, paths } from './gen/frontend'

type Schemas = components['schemas']

export type Environment = Schemas['Environment']
export type CreateEnvironment = Schemas['CreateEnvironment']
export type DesiredState = Schemas['DesiredState']
export type Phase = Schemas['Phase']
export type Worker = Schemas['Worker']
export type Resources = Schemas['Resources']
export type Me = Schemas['Me']
export type User = Schemas['User']
export type CreateUser = Schemas['CreateUser']
export type UpdateUser = Schemas['UpdateUser']

const client = createClient<paths>()

export class ApiError extends Error {
  status: number

  constructor(status: number, message: string) {
    super(message)
    this.status = status
  }
}

// unwrap turns openapi-fetch's { data, error } into a value or a thrown
// ApiError, which is what React Query expects of a query function.
async function unwrap<T>(
  call: Promise<{ data?: T; error?: { error: string } | unknown; response: Response }>,
): Promise<T> {
  const { data, error, response } = await call
  if (!response.ok) {
    const message =
      typeof error === 'object' && error !== null && 'error' in error && typeof error.error === 'string'
        ? error.error
        : response.statusText
    throw new ApiError(response.status, message)
  }
  return data as T
}

const byID = (id: string) => ({ params: { path: { id } } })

export const api = {
  me: () => unwrap(client.GET('/api/frontend/me')),
  login: (username: string, password: string) =>
    unwrap(client.POST('/api/frontend/auth/login', { body: { username, password } })),
  logout: () => unwrap(client.POST('/api/frontend/auth/logout')),
  changePassword: (current_password: string, new_password: string) =>
    unwrap(client.POST('/api/frontend/me/password', { body: { current_password, new_password } })),

  environments: () => unwrap(client.GET('/api/frontend/environments')),
  createEnvironment: (body: CreateEnvironment) => unwrap(client.POST('/api/frontend/environments', { body })),
  startEnvironment: (id: string) => unwrap(client.POST('/api/frontend/environments/{id}/start', byID(id))),
  stopEnvironment: (id: string) => unwrap(client.POST('/api/frontend/environments/{id}/stop', byID(id))),
  deleteEnvironment: (id: string) => unwrap(client.DELETE('/api/frontend/environments/{id}', byID(id))),

  workers: () => unwrap(client.GET('/api/frontend/workers')),
  revokeWorker: (id: string) => unwrap(client.POST('/api/frontend/workers/{id}/revoke', byID(id))),
  deleteWorker: (id: string) => unwrap(client.DELETE('/api/frontend/workers/{id}', byID(id))),

  users: () => unwrap(client.GET('/api/frontend/users')),
  createUser: (body: CreateUser) => unwrap(client.POST('/api/frontend/users', { body })),
  updateUser: (id: string, body: UpdateUser) =>
    unwrap(client.PATCH('/api/frontend/users/{id}', { ...byID(id), body })),
  deleteUser: (id: string) => unwrap(client.DELETE('/api/frontend/users/{id}', byID(id))),
}
