// The frontend API, typed from internal/frontendapi/openapi.yaml. The types in
// gen/ are generated by `npm run gen:api`; a path, parameter or field that
// does not match the spec fails to compile.

import createClient from 'openapi-fetch'

import type { components, paths } from './gen/frontend'

type Schemas = components['schemas']

export type Environment = Schemas['Environment']
export type CreateEnvironment = Schemas['CreateEnvironment']
export type DesiredState = Schemas['DesiredState']
export type Phase = Schemas['Phase']
export type Worker = Schemas['Worker']
export type Resources = Schemas['Resources']
export type Me = Schemas['Me']
export type User = Schemas['User']
export type CreateUser = Schemas['CreateUser']
export type UpdateUser = Schemas['UpdateUser']
export type Profile = Schemas['Profile']
export type Pack = Schemas['Pack']
export type PackInput = Schemas['PackInput']
export type PackPath = Schemas['PackPath']
export type PackRef = Schemas['PackRef']
export type Copy = Schemas['Copy']
export type PackFile = Schemas['PackFile']
export type PackFileContent = Schemas['PackFileContent']
export type AttachedPack = Schemas['AttachedPack']
export type FileConflict = Schemas['FileConflict']
export type SSHKey = Schemas['SSHKey']
export type LoginKey = Schemas['LoginKey']
export type AccessToken = Schemas['AccessToken']
export type AuditEvent = Schemas['AuditEvent']
export type ProcessInfo = Schemas['Process']
export type Spec = Schemas['Spec']
export type Access = Schemas['Access']
export type Repo = Schemas['Repo']
export type Display = Schemas['Display']
export type GPU = Schemas['GPU']
export type Person = Schemas['Person']
export type Team = Schemas['Team']
export type TeamRef = Schemas['TeamRef']
export type TeamRole = Schemas['TeamRole']
export type TeamMember = Schemas['TeamMember']
export type CreateTeam = Schemas['CreateTeam']
export type TeamInput = Schemas['TeamInput']
export type ImageRepository = Schemas['ImageRepository']
export type EnvironmentSettings = Schemas['EnvironmentSettings']
export type LogPart = Schemas['LogPart']
export type EnvironmentLogName = Schemas['EnvironmentLogName']
export type TemplateSetting = Schemas['TemplateSetting']
export type ImageTag = Schemas['ImageTag']
export type ImageRepositoryInput = Schemas['ImageRepositoryInput']
export type Template = Schemas['Template']
export type TemplateInput = Schemas['TemplateInput']
export type Visibility = Schemas['Visibility']
export type WorkerStats = Schemas['WorkerStats']
export type GPUInfo = Schemas['GPUInfo']
export type EnvironmentStats = Schemas['EnvironmentStats']
export type LocalImage = Schemas['LocalImage']
export type TerminalSession = Schemas['TerminalSession']

const client = createClient<paths>()

export class ApiError extends Error {
  status: number

  constructor(status: number, message: string) {
    super(message)
    this.status = status
  }
}

// unwrap turns openapi-fetch's { data, error } into a value or a thrown
// ApiError, which is what React Query expects of a query function.
async function unwrap<T>(
  call: Promise<{ data?: T; error?: { error: string } | unknown; response: Response }>,
): Promise<T> {
  const { data, error, response } = await call
  if (!response.ok) {
    const message =
      typeof error === 'object' && error !== null && 'error' in error && typeof error.error === 'string'
        ? error.error
        : response.statusText
    throw new ApiError(response.status, message)
  }
  return data as T
}

const byID = (id: string) => ({ params: { path: { id } } })

export const api = {
  me: () => unwrap(client.GET('/api/frontend/me')),
  login: (username: string, password: string) =>
    unwrap(client.POST('/api/frontend/auth/login', { body: { username, password } })),
  logout: () => unwrap(client.POST('/api/frontend/auth/logout')),
  changePassword: (current_password: string, new_password: string) =>
    unwrap(client.POST('/api/frontend/me/password', { body: { current_password, new_password } })),

  audit: (subject: string[], before?: number, limit = 50) =>
    unwrap(client.GET('/api/frontend/audit', { params: { query: { subject, before, limit } } })),
  profile: () => unwrap(client.GET('/api/frontend/me/profile')),
  packs: () => unwrap(client.GET('/api/frontend/packs')),
  pack: (id: string) => unwrap(client.GET('/api/frontend/packs/{id}', byID(id))),
  createPack: (body: PackInput) => unwrap(client.POST('/api/frontend/packs', { body })),
  updatePack: (id: string, body: PackInput) => unwrap(client.PUT('/api/frontend/packs/{id}', { ...byID(id), body })),
  deletePack: (id: string) => unwrap(client.DELETE('/api/frontend/packs/{id}', byID(id))),
  copies: (pack: string) => unwrap(client.GET('/api/frontend/packs/{id}/copies', byID(pack))),
  createCopy: (pack: string, name: string, team_id?: string) =>
    unwrap(client.POST('/api/frontend/packs/{id}/copies', { ...byID(pack), body: { name, team_id } })),
  setDefaultCopy: (pack: string, copy_id?: string) =>
    unwrap(client.PUT('/api/frontend/packs/{id}/default', { ...byID(pack), body: { copy_id } })),
  copy: (id: string) => unwrap(client.GET('/api/frontend/copies/{id}', byID(id))),
  renameCopy: (id: string, name: string) =>
    unwrap(client.PATCH('/api/frontend/copies/{id}', { ...byID(id), body: { name } })),
  deleteCopy: (id: string) => unwrap(client.DELETE('/api/frontend/copies/{id}', byID(id))),
  copyFile: (id: string, path: string) =>
    unwrap(client.GET('/api/frontend/copies/{id}/file', { params: { path: { id }, query: { path } } })),
  putCopyFile: (id: string, path: string, content: string) =>
    unwrap(
      client.PUT('/api/frontend/copies/{id}/file', { params: { path: { id }, query: { path } }, body: { content } }),
    ),
  setCopyFileMode: (id: string, path: string, mode: number) =>
    unwrap(
      client.PATCH('/api/frontend/copies/{id}/file', { params: { path: { id }, query: { path } }, body: { mode } }),
    ),
  deleteCopyFile: (id: string, path: string) =>
    unwrap(client.DELETE('/api/frontend/copies/{id}/file', { params: { path: { id }, query: { path } } })),
  environmentPacks: (id: string) => unwrap(client.GET('/api/frontend/environments/{id}/packs', byID(id))),
  chooseEnvironmentCopy: (id: string, pack: string, copy_id?: string) =>
    unwrap(
      client.PUT('/api/frontend/environments/{id}/packs/{pack}', {
        params: { path: { id, pack } },
        body: { copy_id },
      }),
    ),
  environmentConflicts: (id: string) => unwrap(client.GET('/api/frontend/environments/{id}/conflicts', byID(id))),
  resolveConflict: (id: string, copy_id: string, path: string, resolution: 'shared' | 'environment') =>
    unwrap(
      client.POST('/api/frontend/environments/{id}/conflicts', { ...byID(id), body: { copy_id, path, resolution } }),
    ),
  addSSHKey: (name: string, private_key?: string) =>
    unwrap(client.POST('/api/frontend/me/profile/keys', { body: { name, private_key } })),
  deleteSSHKey: (id: string) => unwrap(client.DELETE('/api/frontend/me/profile/keys/{id}', byID(id))),
  addLoginKey: (public_key: string, name?: string) =>
    unwrap(client.POST('/api/frontend/me/profile/login-keys', { body: { public_key, name } })),
  deleteLoginKey: (id: string) => unwrap(client.DELETE('/api/frontend/me/profile/login-keys/{id}', byID(id))),
  tokens: () => unwrap(client.GET('/api/frontend/me/tokens')),
  createToken: (name: string, expires_in_days?: number) =>
    unwrap(client.POST('/api/frontend/me/tokens', { body: { name, expires_in_days } })),
  revokeToken: (id: string) => unwrap(client.DELETE('/api/frontend/me/tokens/{id}', byID(id))),

  environments: () => unwrap(client.GET('/api/frontend/environments')),
  createEnvironment: (body: CreateEnvironment) => unwrap(client.POST('/api/frontend/environments', { body })),
  startEnvironment: (id: string) => unwrap(client.POST('/api/frontend/environments/{id}/start', byID(id))),
  stopEnvironment: (id: string) => unwrap(client.POST('/api/frontend/environments/{id}/stop', byID(id))),
  updateEnvironmentSettings: (id: string, body: EnvironmentSettings) =>
    unwrap(client.PUT('/api/frontend/environments/{id}/settings', { ...byID(id), body })),
  resetEnvironmentToTemplate: (id: string) =>
    unwrap(client.POST('/api/frontend/environments/{id}/reset-to-template', byID(id))),
  setEnvironmentPorts: (id: string, pub: boolean) =>
    unwrap(client.PUT('/api/frontend/environments/{id}/ports', { ...byID(id), body: { public: pub } })),
  upgradeEnvironmentImage: (id: string, force: boolean) =>
    unwrap(client.POST('/api/frontend/environments/{id}/image/upgrade', { ...byID(id), body: { force } })),
  rollbackEnvironmentImage: (id: string) =>
    unwrap(client.POST('/api/frontend/environments/{id}/image/rollback', byID(id))),
  keepEnvironmentImage: (id: string) => unwrap(client.POST('/api/frontend/environments/{id}/image/keep', byID(id))),
  cancelEnvironmentImageChange: (id: string) =>
    unwrap(client.POST('/api/frontend/environments/{id}/image/cancel', byID(id))),
  suspendEnvironment: (id: string) => unwrap(client.POST('/api/frontend/environments/{id}/suspend', byID(id))),
  resizeDesktop: (id: string, width: number, height: number) =>
    unwrap(
      client.PUT('/api/frontend/environments/{id}/desktop/size', { params: { path: { id } }, body: { width, height } }),
    ),
  openEditor: (id: string) => unwrap(client.POST('/api/frontend/environments/{id}/editor', byID(id))),
  environmentLog: (id: string, log: EnvironmentLogName, offset?: number) =>
    unwrap(
      client.GET('/api/frontend/environments/{id}/logs/{log}', {
        params: { path: { id, log }, query: offset === undefined ? {} : { offset } },
      }),
    ),
  workerLog: (id: string, offset?: number) =>
    unwrap(
      client.GET('/api/frontend/workers/{id}/log', {
        params: { path: { id }, query: offset === undefined ? {} : { offset } },
      }),
    ),
  processes: (id: string) => unwrap(client.GET('/api/frontend/environments/{id}/processes', byID(id))),
  signalProcess: (id: string, pid: number, signal: 'TERM' | 'KILL') =>
    unwrap(
      client.POST('/api/frontend/environments/{id}/processes/{pid}/signal', {
        params: { path: { id, pid } },
        body: { signal },
      }),
    ),
  terminals: (id: string) => unwrap(client.GET('/api/frontend/environments/{id}/terminals', byID(id))),
  closeTerminal: (id: string, session: string) =>
    unwrap(
      client.DELETE('/api/frontend/environments/{id}/terminals/{session}', { params: { path: { id, session } } }),
    ),
  deleteEnvironment: (id: string) => unwrap(client.DELETE('/api/frontend/environments/{id}', byID(id))),

  templates: () => unwrap(client.GET('/api/frontend/templates')),
  template: (id: string) => unwrap(client.GET('/api/frontend/templates/{id}', byID(id))),
  createTemplate: (body: TemplateInput) => unwrap(client.POST('/api/frontend/templates', { body })),
  updateTemplate: (id: string, body: TemplateInput) =>
    unwrap(client.PUT('/api/frontend/templates/{id}', { ...byID(id), body })),
  deleteTemplate: (id: string) => unwrap(client.DELETE('/api/frontend/templates/{id}', byID(id))),
  setCollaborators: (id: string, user_ids: string[], team_ids: string[]) =>
    unwrap(client.PUT('/api/frontend/templates/{id}/collaborators', { ...byID(id), body: { user_ids, team_ids } })),
  people: () => unwrap(client.GET('/api/frontend/people')),

  images: () => unwrap(client.GET('/api/frontend/images')),
  image: (id: string) => unwrap(client.GET('/api/frontend/images/{id}', byID(id))),
  updateImage: (id: string, body: ImageRepositoryInput) =>
    unwrap(client.PATCH('/api/frontend/images/{id}', { ...byID(id), body })),
  deleteImage: (id: string) => unwrap(client.DELETE('/api/frontend/images/{id}', byID(id))),
  setImageCollaborators: (id: string, user_ids: string[], team_ids: string[]) =>
    unwrap(client.PUT('/api/frontend/images/{id}/collaborators', { ...byID(id), body: { user_ids, team_ids } })),
  deleteImageTag: (id: string, tag: string) =>
    unwrap(client.DELETE('/api/frontend/images/{id}/tags/{tag}', { params: { path: { id, tag } } })),

  teams: () => unwrap(client.GET('/api/frontend/teams')),
  team: (id: string) => unwrap(client.GET('/api/frontend/teams/{id}', byID(id))),
  createTeam: (body: CreateTeam) => unwrap(client.POST('/api/frontend/teams', { body })),
  updateTeam: (id: string, body: TeamInput) => unwrap(client.PATCH('/api/frontend/teams/{id}', { ...byID(id), body })),
  deleteTeam: (id: string) => unwrap(client.DELETE('/api/frontend/teams/{id}', byID(id))),
  setTeamMember: (id: string, user: string, role: TeamRole) =>
    unwrap(client.PUT('/api/frontend/teams/{id}/members/{user}', { params: { path: { id, user } }, body: { role } })),
  removeTeamMember: (id: string, user: string) =>
    unwrap(client.DELETE('/api/frontend/teams/{id}/members/{user}', { params: { path: { id, user } } })),

  workers: () => unwrap(client.GET('/api/frontend/workers')),
  worker: (id: string) => unwrap(client.GET('/api/frontend/workers/{id}', byID(id))),
  removeWorkerImage: (id: string, ref: string, digest: string) =>
    unwrap(client.POST('/api/frontend/workers/{id}/images/remove', { ...byID(id), body: { ref, digest } })),
  removeUnknownEnvironments: (id: string, environments: string[]) =>
    unwrap(client.POST('/api/frontend/workers/{id}/unknown/remove', { ...byID(id), body: { environments } })),
  revokeWorker: (id: string) => unwrap(client.POST('/api/frontend/workers/{id}/revoke', byID(id))),
  deleteWorker: (id: string) => unwrap(client.DELETE('/api/frontend/workers/{id}', byID(id))),

  users: () => unwrap(client.GET('/api/frontend/users')),
  createUser: (body: CreateUser) => unwrap(client.POST('/api/frontend/users', { body })),
  updateUser: (id: string, body: UpdateUser) =>
    unwrap(client.PATCH('/api/frontend/users/{id}', { ...byID(id), body })),
  deleteUser: (id: string) => unwrap(client.DELETE('/api/frontend/users/{id}', byID(id))),
}
